version: '3.8'

services:
  rfid-reader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rfid-reader
    environment:
      - READER_IP_ADDRESS=10.10.69.69
      - HTTP_PORT=3001
      - ASPNETCORE_URLS=http://+:3001
    ports:
      - "3001:3001"
    networks:
      - rfid-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  rfid-network:
    name: rfid-network
    driver: bridge